<script lang="ts">
	import { onMount } from 'svelte';
	import { getProductStore } from '$lib/product/state.svelte';
	const store = getProductStore();
	let step = $state(0);
	let mlReady = $state(false);
	let flReady = $state(false);
	let evidenceError = $state<string | null>(null);
	const steps = [
		{ title: 'What NHM is', happens: 'A research monitoring product with a simulated source, a released centrally trained model, and a separate engineering federation lane.', why: 'Separate the current monitoring runtime from development experiments.', know: 'The System, Models, and About views expose the active bindings and claim boundaries.', limit: 'Not diagnostic, clinical, or physical-wearable validated.', href: '/app/about', action: 'Read scope and limitations' },
		{ title: 'A signal enters', happens: 'Select a real deterministic synthetic source window and inspect the samples used by the canonical streaming operators.', why: 'The source must be visible before downstream claims make sense.', know: 'The Signal Journey calls the additive bounded trace API.', limit: 'A scenario reconstruction is not a captured historical stream.', href: '/app/observatory', action: 'Inspect the signal' },
		{ title: 'Gaps and causal preprocessing', happens: 'Missing source positions, causal gap policy, resampling, and ECG filtering are shown as separate stages.', why: 'Missing data and stateful transforms change which windows remain usable.', know: 'Stage plots are captured from delegated canonical operators and parity-tested against the unobserved runtime.', limit: 'Only a selected bounded interval is displayed; plotted points are decimated.', href: '/app/observatory/scenarios', action: 'Open the scenario and fault lab' },
		{ title: 'Ten-second windows', happens: 'Move the selected window by the actual five-second cadence and compare overlapping samples.', why: 'Windowing defines the exact model input and source-time decision point.', know: 'The Observatory uses the canonical streaming window sequence index and source timestamp.', limit: 'Overlapping windows are not independent patients.', href: '/app/observatory', action: 'Scrub a window' },
		{ title: 'Quality and context', happens: 'Review actual VALID, DEGRADED, or UNUSABLE quality and separate ECG from PPG/SpO₂ context.', why: 'Signal usability and monitoring state answer different questions.', know: 'Quality reasons come from the canonical runtime; owned-session context comes only from public projected snapshots.', limit: 'QUALITY_V1 has a known stuck-nonzero limitation.', href: '/app/observatory', action: 'Inspect a quality gate' },
		{ title: 'Model input and monitoring', happens: 'View per-window normalized model input, then attach persisted inference metadata from an owned session where available.', why: 'The browser does not run inference; the released server-side runtime does.', know: 'The trace contains a tensor digest; recorded outputs come from persisted inference events.', limit: 'Scenario-only reconstruction has no model output, and the Observatory never reruns inference.', href: '/app/monitoring', action: 'Run research monitoring' },
		{ title: 'Research records and labels', happens: 'Inspect a hash-verified, processed MIT-BIH TRAIN window separately from synthetic event labels.', why: 'AAMI-SVF annotated ECG classification and wearable simulation events are different targets.', know: 'The record inspector checks the frozen TRAIN split, cache, example ID, and manifest before serving a bounded waveform.', limit: 'Raw WFDB beat positions are unavailable locally; no held-out waveform or new scientific label is accessed.', href: '/app/observatory/research', action: 'Inspect a TRAIN record' },
		{ title: 'Model decision history', happens: 'Read the historical NOT_PROMOTED model gate beside the later accepted research software release.', why: 'The two decisions used different criteria and neither rewrites the other.', know: 'Both decisions and their frozen provenance are on the ML research page.', limit: 'The release is not clinical validation.', href: '/app/observatory/provenance', action: 'Open decision history and boundaries' },
		{ title: 'Eight synthetic participants', happens: 'Inspect every logical client, its frozen source profile, fault schedule, eligibility, and engineering-label balance.', why: 'Each participant contributes a different local training dataset.', know: 'The roster is loaded from a hash-identified frozen cohort manifest.', limit: 'All clients run on one demonstration machine; they are synthetic logical clients, not real sites.', href: '/app/observatory/federation', action: 'Explore the clients' },
		{ title: 'Local optimization', happens: 'A live product federation run performs genuine local model optimization using the synthetic training buffers.', why: 'Local updates are computed rather than animated into existence.', know: 'The Federation Studio journal reports training milestones; run artifacts preserve examples seen, seed, and update digest.', limit: 'Batch-level loss and update norm are not persisted for older runs; this tour does not invent them.', href: '/app/federation/live', action: 'Open a live or historical run' },
		{ title: 'Accepted contribution', happens: 'Compare accepted examples and the resulting sample-count weights only where their evidence reconciles.', why: 'Only accepted updates belong in the aggregation denominator.', know: 'Intermediate rounds use direct coordinator maps; the final round requires the server journal and persisted governance attestation.', limit: 'A SUBMITTED UI state alone is not acceptance; the final-round map is not directly persisted, so missing attestation remains unknown.', href: '/app/observatory/federation', action: 'Inspect round accounting' },
		{ title: 'Global state and candidate', happens: 'Follow reported round base and committed digests to a separate sandbox engineering candidate.', why: 'A changed state digest shows state evolution, not improved scientific performance.', know: 'The Federation Studio and Models registry expose event and governance evidence.', limit: 'Candidate efficacy and calibration are not established; it is not deployed.', href: '/app/models', action: 'Inspect model governance' },
		{ title: 'Scientific FL evidence', happens: 'Read frozen IID, non-IID, FedProx, held-out, and narrow SecAgg research evidence.', why: 'The research experiments are distinct from the short synthetic product demo.', know: 'The FL research API is backed by a hash-bound frozen evidence catalog.', limit: 'V2-FL-005 is engineering evidence only; SecAgg does not establish DP or anonymity.', href: '/app/observatory/evidence', action: 'Open the scientific evidence explorer' },
		{ title: 'Provenance and reproducibility', happens: 'Open exact source paths, digests, IDs, and accepted claims wherever the product provides them.', why: 'An evaluator should be able to trace a statement back to evidence.', know: 'The System view, research provenance panels, and Observatory technical disclosures carry source identities.', limit: 'A report existing is not the same as independently reproducing its result.', href: '/app/observatory/provenance', action: 'Open the reproducibility console' },
		{ title: 'Known boundaries', happens: 'Review calibration domain, small patient-group counts, second-look evidence, simulated-only source, and sandbox boundaries.', why: 'Negative findings are part of the result.', know: 'The research and About pages retain their frozen limitation language.', limit: 'No clinical, hospital privacy, personalized-model, or production-security claim is made.', href: '/app/observatory/provenance', action: 'Open known boundaries' },
		{ title: 'What has been demonstrated', happens: 'A working research monitoring runtime, persisted product history, genuine short FL engineering run, and separate frozen scientific evidence.', why: 'The final synthesis should not flatten scientific efficacy and engineering mechanism into one claim.', know: 'Revisit each linked source rather than relying on the tour alone.', limit: 'Future candidate efficacy requires a separate compatible predeclared experiment.', href: '/app/observatory', action: 'Return to the Observatory' }
	];
	const active = $derived(steps[step]);
	onMount(() => { void Promise.all([store.api.researchMl(), store.api.researchFl()]).then(() => {
		mlReady = true; flReady = true;
	}).catch((cause) => { evidenceError = cause instanceof Error ? cause.message : String(cause); }); });
	function move(delta: number) { step = Math.min(steps.length - 1, Math.max(0, step + delta)); }
</script>
<svelte:head><title>Guided Research Observatory | NHM</title></svelte:head>
<div class="eyebrow">NHM / RESEARCH OBSERVATORY / GUIDED</div>
<h1>Follow the evidence, end to end</h1>
<p class="lead">A faculty-friendly path through the real implementation. Each step links to the live product or frozen evidence; the tour itself does not run a model or training job.</p>
<div class="layout"><nav aria-label="Tour steps"><ol>{#each steps as item, index}<li><button class:active={step===index} aria-current={step===index ? 'step' : undefined} onclick={()=>step=index}><small>{String(index+1).padStart(2,'0')}</small>{item.title}</button></li>{/each}</ol></nav>
	<section class="tour-main"><div class="progress">STEP {step+1} / {steps.length} <span>{Math.round((step+1)/steps.length*100)}% of guide</span></div><div class="progress-track"><i style={`width:${(step+1)/steps.length*100}%`}></i></div>
		<article><span>GUIDED EXPLANATION</span><h2>{active.title}</h2><div class="cards"><section><h3>What is happening?</h3><p>{active.happens}</p></section><section><h3>Why does NHM do this?</h3><p>{active.why}</p></section><section><h3>How do we know?</h3><p>{active.know}</p></section><section class="limit"><h3>What does this not prove?</h3><p>{active.limit}</p></section></div><a class="action" href={active.href}>{active.action} →</a></article>
		{#if evidenceError}<p role="alert" class="error">Frozen research API unavailable: {evidenceError}. Research steps remain navigable, but API evidence has not been verified in this tour session.</p>{:else}<p class="status">Research APIs: ML {mlReady ? 'LOADED' : 'CHECKING'} · FL {flReady ? 'LOADED' : 'CHECKING'}.</p>{/if}
		<div class="controls"><button onclick={()=>move(-1)} disabled={step===0}>← Previous</button><button onclick={()=>move(1)} disabled={step===steps.length-1}>Next →</button><a href="/app/observatory">Exit guided mode</a></div>
	</section></div>
<style>
	.eyebrow,.progress,article>span{color:#2bb8b0;font:10px 'JetBrains Mono',monospace;letter-spacing:.14em}h1{font:500 clamp(28px,4vw,42px) 'Space Grotesk',sans-serif;margin:8px 0}.lead{max-width:800px;color:#a7b8c9;line-height:1.6}.layout{display:grid;grid-template-columns:250px minmax(0,1fr);gap:22px;margin-top:25px;min-width:0}.layout>.tour-main{min-width:0}nav{border:1px solid #334155;background:#071421;align-self:start;min-width:0;max-width:100%;overflow-x:auto}ol{list-style:none;margin:0;padding:8px}li button{display:flex;gap:10px;align-items:center;width:100%;background:none;border:1px solid transparent;color:#a7b8c9;text-align:left;min-height:36px;padding:7px;cursor:pointer;font-size:12px}li button.active{border-color:#2bb8b0;background:#0b262b;color:#fff}li small{font:10px 'JetBrains Mono',monospace;color:#2bb8b0}.progress{display:flex;justify-content:space-between}.progress span{color:#94a3b8}.progress-track{height:3px;background:#1e293b;margin:9px 0 18px}.progress-track i{display:block;height:100%;background:#2bb8b0}article{border:1px solid #334155;padding:22px;background:#071421}h2{font:500 clamp(24px,3vw,32px) 'Space Grotesk',sans-serif;margin:8px 0 20px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cards section{border:1px solid #334155;padding:15px;min-height:110px}.cards .limit{border-color:#885f22;background:#1b1711}h3{font:11px 'JetBrains Mono',monospace;color:#2bb8b0;margin:0 0 10px}.limit h3{color:#fbbf24}.cards p{margin:0;color:#b9cad7;line-height:1.6;font-size:14px}.action{display:inline-block;margin-top:18px;border:1px solid #2bb8b0;padding:11px 14px;color:#7ee4dc;text-decoration:none}.status,.error{font:12px 'JetBrains Mono',monospace;color:#94a3b8}.error{color:#f87171}.controls{display:flex;gap:9px;align-items:center;margin-top:20px}.controls button{min-height:38px;padding:8px 12px;background:#0b262b;border:1px solid #2bb8b0;color:#e5f1f0;cursor:pointer}.controls button:disabled{opacity:.4;cursor:not-allowed}.controls a{color:#2bb8b0;margin-left:auto}button:focus-visible,a:focus-visible{outline:2px solid #fbbf24;outline-offset:2px}@media(max-width:800px){.layout{grid-template-columns:minmax(0,1fr)}nav ol{display:flex;width:max-content}li button{min-width:130px;height:50px}}@media(max-width:550px){.cards{grid-template-columns:1fr}article{padding:14px}.controls{flex-wrap:wrap}.controls a{margin-left:0;width:100%}}
	a{display:inline-block;min-height:24px;line-height:24px}
</style>
