# ruff: noqa: E501
"""Independent synthetic evaluation cohort for NHM_SYNTH_FL_EVAL_PROTOCOL_V1 (participant-level separation).

Eight held-out virtual participants (SIM_P000201..208), one per frozen synthetic site condition, generated by the EXISTING deterministic
generator (simulation.fl_cohort_v1) with a different base seed, different participant identities, different session identities and
independently drawn event schedules. They never enter a training buffer or an optimizer. Parameters below were fixed before any candidate
prediction was computed and must not be changed afterwards."""

from __future__ import annotations

from typing import Any

from federated.virtual_client_source_v1 import LocalDataset, build_local_dataset
from federated.wearable_sim_local_labels import SyntheticEventLabelProvider, SyntheticObservedSource
from simulation import fl_cohort_v1 as cohort
from simulation.fl_cohort_v1 import ClientProfile
from simulation.wearable import participant_id_for_index

HOLDOUT_COHORT_ID = "WEARABLE_SIM_FL_EVAL_HOLDOUT_V1"
HOLDOUT_BASE_SEED = 20261009            # predeclared; distinct from the training cohort BASE_SEED 20260927
FIRST_HOLDOUT_PARTICIPANT_INDEX = 201   # training participants are 101..108
HOLDOUT_COUNT = 8


def holdout_id(index: int) -> str:
    return f"SIM_FL_EVAL_{index:02d}"


def holdout_profile(index: int) -> ClientProfile:
    """Same site-condition template (faults/context/heart-rate convention) as training site ``index``; everything random is re-drawn."""
    if not 0 <= index < HOLDOUT_COUNT:
        raise ValueError("HOLDOUT_INDEX_OUT_OF_RANGE")
    participant_index = FIRST_HOLDOUT_PARTICIPANT_INDEX + index
    return ClientProfile(
        client_id=holdout_id(index), participant_index=participant_index, participant_id=participant_id_for_index(participant_index),
        session_id=f"SIM_S_FLEVAL_{index:02d}_000001", seed=HOLDOUT_BASE_SEED + index, base_hr_bpm=float(66 + 3 * index),
        faults=cohort._FAULTS[index], context=cohort._CONTEXT[index], events=cohort._schedule_events(index, HOLDOUT_BASE_SEED),
        coverage=cohort._COVERAGE[index])


def holdout_profiles() -> tuple[ClientProfile, ...]:
    return tuple(holdout_profile(i) for i in range(HOLDOUT_COUNT))


def build_holdout_dataset(profile: ClientProfile) -> LocalDataset:
    """The unchanged canonical builder: stream runtime -> QUALITY_V1 -> trainable rule -> WEARABLE_SIM_EVENT_WINDOW_V1 labels -> per-window z-score."""
    return build_local_dataset(SyntheticObservedSource(profile), SyntheticEventLabelProvider(profile))


def manifest_entry(profile: ClientProfile, dataset: LocalDataset, site_index: int) -> dict[str, Any]:
    return {"holdout_id": profile.client_id, "participant_id": profile.participant_id, "session_id": profile.session_id, "seed": profile.seed,
            "mirrors_training_site_condition": cohort.client_id(site_index), "coverage": list(profile.coverage),
            "event_times_s": [e.time_s for e in profile.events], "event_kinds": [e.kind for e in profile.events],
            "counts": dataset.counts, "dataset_sha256": dataset.dataset_sha256}
