"""V2-003 pre-run tests (Section 27): exact feature schema/order, variant dimensions, no
annotation/quality/ID feature, TRAIN-only feature loader, official-VALIDATION access blocked,
INNER_VALIDATION never permitted, OUTER_TEST cannot enter fit transforms, fold-local
imputer/scaler scope, frozen LR/RF config equality, and firewall/grouping invariants. All
synthetic/metadata-only -- no real OUTER_TEST result is generated by this module.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import yaml

import scripts._v2_003_lib as lib
from features.ecg import BASELINE_FEATURE_NAMES_V1
from nhm.model_v2_cv_role_guard import CVRoleAccessViolation, check_cv_role_allowed
from nhm.model_v2_partition_guard import PartitionAccessViolation, check_partition_allowed

ROOT = Path(__file__).resolve().parents[1]


def test_exact_29_feature_names_and_order() -> None:
    assert len(BASELINE_FEATURE_NAMES_V1) == 29
    assert BASELINE_FEATURE_NAMES_V1[0] == "ecg_mean"
    assert BASELINE_FEATURE_NAMES_V1[13] == "detected_beat_count"
    assert BASELINE_FEATURE_NAMES_V1[22] == "qrs_peak_absolute_mean"
    assert BASELINE_FEATURE_NAMES_V1[28] == "qrs_available"


def test_stat_rr_qrs_indices_exact() -> None:
    assert tuple(range(0, 13)) == lib.STAT_INDICES
    assert tuple(range(13, 22)) == lib.RR_INDICES
    assert tuple(range(22, 29)) == lib.QRS_INDICES
    names = BASELINE_FEATURE_NAMES_V1
    assert [names[i] for i in lib.STAT_INDICES] == [
        "ecg_mean", "ecg_std", "ecg_median", "ecg_mad", "ecg_rms", "ecg_min", "ecg_max",
        "ecg_peak_to_peak", "ecg_iqr", "ecg_mean_absolute", "ecg_skewness", "ecg_kurtosis",
        "ecg_mean_absolute_difference",
    ]
    assert [names[i] for i in lib.RR_INDICES] == [
        "detected_beat_count", "rr_mean_seconds", "rr_median_seconds", "rr_std_seconds",
        "rr_min_seconds", "rr_max_seconds", "rr_rmssd_seconds", "detected_hr_mean_bpm",
        "rr_available",
    ]
    assert [names[i] for i in lib.QRS_INDICES] == [
        "qrs_peak_absolute_mean", "qrs_peak_absolute_std", "qrs_local_energy_mean",
        "qrs_local_energy_std", "qrs_local_max_slope_mean",
        "qrs_width_half_prominence_mean_ms", "qrs_available",
    ]


@pytest.mark.parametrize(
    "variant,expected_count",
    [
        ("STAT", 13), ("RR", 9), ("QRS", 7), ("RR_QRS", 16),
        ("STAT_RR", 22), ("STAT_QRS", 20), ("ALL", 29),
    ],
)
def test_variant_dimensions_exact(variant: str, expected_count: int) -> None:
    assert len(lib.VARIANT_INDICES[variant]) == expected_count


def test_seven_variants_in_predeclared_order() -> None:
    assert lib.VARIANT_IDS == ("STAT", "RR", "QRS", "RR_QRS", "STAT_RR", "STAT_QRS", "ALL")


def test_rr_qrs_and_stat_unions_disjoint_and_complete() -> None:
    stat = set(lib.STAT_INDICES)
    rr = set(lib.RR_INDICES)
    qrs = set(lib.QRS_INDICES)
    assert stat & rr == set()
    assert rr & qrs == set()
    assert stat & qrs == set()
    assert stat | rr | qrs == set(range(29))
    assert set(lib.VARIANT_INDICES["RR_QRS"]) == rr | qrs
    assert set(lib.VARIANT_INDICES["STAT_RR"]) == stat | rr
    assert set(lib.VARIANT_INDICES["STAT_QRS"]) == stat | qrs
    assert set(lib.VARIANT_INDICES["ALL"]) == stat | rr | qrs


def test_no_annotation_quality_or_id_feature() -> None:
    forbidden_substrings = ("annotation", "aami", "symbol", "quality", "patient_id", "record_id")
    for name in BASELINE_FEATURE_NAMES_V1:
        lowered = name.lower()
        assert not any(bad in lowered for bad in forbidden_substrings), name


def test_feature_schema_hash_matches_frozen_lock() -> None:
    lock = json.loads(lib.BASELINE_V1_LOCK.read_text(encoding="utf-8"))
    schema = json.loads(lib.FEATURE_SCHEMA_PATH.read_text(encoding="utf-8"))
    assert schema["feature_schema_sha256"] == lock["feature_schema_sha256"]
    assert schema["feature_count"] == 29


def test_config_binds_margin_and_seeds() -> None:
    config = lib.load_config()
    assert config["minimal_adequate_subset_rule"]["margin_absolute_auprc"] == 0.02
    assert config["grouped_permutation_importance"]["seed"] == 20261003
    assert config["grouped_permutation_importance"]["repetitions"] == 50
    assert config["bootstrap"]["bootstrap_seed"] == 20261002
    assert config["fit_scope"]["inner_validation_used"] is False
    assert config["hybrid_trigger"]["status"] == "PENDING_V2_004"


def test_lr_config_equals_frozen_t014_config() -> None:
    baseline_config = yaml.safe_load((ROOT / "configs/baseline_v1.yaml").read_text())
    config = lib.load_config()
    frozen = baseline_config["logistic_regression"]
    audit = config["model_configs"]["LOGISTIC"]["params"]
    assert audit["C"] == frozen["C"]
    assert audit["solver"] == frozen["solver"]
    assert audit["max_iter"] == frozen["max_iter"]
    assert audit["class_weight"] == frozen["class_weight"]
    assert audit["random_state"] == frozen["random_state"]


def test_rf_config_equals_frozen_t014_config() -> None:
    baseline_config = yaml.safe_load((ROOT / "configs/baseline_v1.yaml").read_text())
    config = lib.load_config()
    frozen = baseline_config["random_forest"]
    audit = config["model_configs"]["RF"]["params"]
    assert audit["n_estimators"] == frozen["n_estimators"]
    assert audit["max_depth"] == frozen["max_depth"]
    assert audit["max_features"] == frozen["max_features"]
    assert audit["class_weight"] == frozen["class_weight"]
    assert audit["random_state"] == frozen["random_state"]
    assert audit["n_jobs"] == frozen["n_jobs"] == 1


def test_create_logistic_regression_matches_config() -> None:
    model = lib.create_logistic_regression()
    assert model.get_params()["C"] == 1.0
    assert model.get_params()["solver"] == "liblinear"
    assert model.get_params()["random_state"] == 20260927


def test_create_random_forest_matches_config() -> None:
    model = lib.create_random_forest()
    params = model.get_params()
    assert params["n_estimators"] == 200
    assert params["max_depth"] == 12
    assert params["random_state"] == 20260927
    assert params["n_jobs"] == 1


def test_feature_loader_rejects_non_train_partition() -> None:
    with pytest.raises(PartitionAccessViolation):
        check_partition_allowed("VALIDATION", lib.TASK_ID, {"TRAIN"})


def test_train_only_allowed() -> None:
    check_partition_allowed("TRAIN", lib.TASK_ID, {"TRAIN"})  # must not raise


def test_inner_validation_never_permitted_in_v2_003() -> None:
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "INNER_VALIDATION", "V2-003_FIT", requested_outer_fold=0, experiment_outer_fold=0
        )
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "INNER_VALIDATION", "V2-003_EVAL", requested_outer_fold=0, experiment_outer_fold=0
        )


def test_optimise_permitted_only_for_fit_stage() -> None:
    check_cv_role_allowed(
        "OPTIMISE", "V2-003_FIT", requested_outer_fold=0, experiment_outer_fold=0
    )  # must not raise
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OPTIMISE", "V2-003_EVAL", requested_outer_fold=0, experiment_outer_fold=0
        )


def test_outer_test_cannot_enter_fit_stage() -> None:
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OUTER_TEST", "V2-003_FIT", requested_outer_fold=0, experiment_outer_fold=0
        )


def test_outer_test_blocked_until_fit_scope_finalized() -> None:
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OUTER_TEST",
            "V2-003_EVAL",
            requested_outer_fold=0,
            experiment_outer_fold=0,
            checkpoint_finalized=False,
        )
    check_cv_role_allowed(
        "OUTER_TEST",
        "V2-003_EVAL",
        requested_outer_fold=0,
        experiment_outer_fold=0,
        checkpoint_finalized=True,
    )  # must not raise


def test_wrong_fold_rejected_both_stages() -> None:
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OPTIMISE", "V2-003_FIT", requested_outer_fold=1, experiment_outer_fold=0
        )
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OUTER_TEST",
            "V2-003_EVAL",
            requested_outer_fold=1,
            experiment_outer_fold=0,
            checkpoint_finalized=True,
        )


def test_v2_002_stages_unaffected_by_v2_003_extension() -> None:
    check_cv_role_allowed(
        "OPTIMISE", "V2-002_TRAIN_SELECT", requested_outer_fold=0, experiment_outer_fold=0
    )
    check_cv_role_allowed(
        "INNER_VALIDATION",
        "V2-002_TRAIN_SELECT",
        requested_outer_fold=0,
        experiment_outer_fold=0,
    )
    with pytest.raises(CVRoleAccessViolation):
        check_cv_role_allowed(
            "OUTER_TEST", "V2-002_TRAIN_SELECT", requested_outer_fold=0, experiment_outer_fold=0
        )


def test_role_closure_matches_v2_002_for_all_folds() -> None:
    for fold in lib.OUTER_FOLDS:
        roles = lib.role_groups_for_fold(fold)
        lib.verify_role_closure(roles)


def test_fold_local_transform_fit_scope_is_optimise_only() -> None:
    rng = np.random.default_rng(0)
    train = rng.normal(size=(20, 5))
    train[0, 0] = np.nan
    imputer, scaler = lib.fit_fold_local_transform(train)
    assert imputer.statistics_.shape == (5,)
    assert scaler.mean_.shape == (5,)
    # A disjoint, differently-distributed OUTER_TEST-shaped batch must use (not refit) these.
    outer = rng.normal(loc=100.0, size=(8, 5))
    transformed = scaler.transform(imputer.transform(outer))
    assert not np.allclose(transformed, 0.0)


def test_rf_never_receives_outer_fit_transforms() -> None:
    config = lib.load_config()
    assert config["model_configs"]["RF"]["scaling"] == "FOLD_LOCAL_IMPUTER_ONLY_NO_SCALER"
    assert config["model_configs"]["LOGISTIC"]["scaling"] == (
        "FOLD_LOCAL_IMPUTER_THEN_STANDARD_SCALER"
    )


def test_no_feature_selection_search_path_exists() -> None:
    config = lib.load_config()
    assert len(config["variants"]) == 7
    variant_ids = [v["id"] for v in config["variants"]]
    assert variant_ids == list(lib.VARIANT_IDS)
    assert "top_k" not in json.dumps(config).lower()
    assert "forward_selection" not in json.dumps(config).lower()
    assert "backward_selection" not in json.dumps(config).lower()


def test_search_budget_unchanged_by_classical_fits() -> None:
    config = lib.load_config()
    assert config["search_budget"]["v2_003_neural_fits"] == 0
    assert config["search_budget"]["cumulative_neural_budget"] == "15/100"
    assert config["search_budget"]["classical_canonical_fits"] == 70


def test_hybrid_trigger_pending() -> None:
    config = lib.load_config()
    assert config["hybrid_trigger"]["status"] == "PENDING_V2_004"


def test_minimal_adequate_subset_candidates_exclude_all() -> None:
    config = lib.load_config()
    candidates = config["minimal_adequate_subset_rule"]["candidates"]
    assert "ALL" not in candidates
    assert set(candidates) == {"STAT", "RR", "QRS", "RR_QRS", "STAT_RR", "STAT_QRS"}


def test_total_canonical_fits_is_70() -> None:
    config = lib.load_config()
    assert config["total_canonical_fits"] == 7 * 2 * 5 == 70
