# ruff: noqa: E501
"""FL10 fresh independent evaluation cohort: 16 participants, two independent profiles for each of the eight established site conditions.

Generated by the EXISTING deterministic generator through the unmodified dataset builder. Distinct participant ids (SIM_P000301-316), seeds, sessions and event schedules
from the training cohort, the previously exposed 8-participant synthetic holdout and the live-monitored session."""

from __future__ import annotations

from typing import Any

from federated.virtual_client_source_v1 import LocalDataset, build_local_dataset
from federated.wearable_sim_local_labels import SyntheticEventLabelProvider, SyntheticObservedSource
from simulation import fl_cohort_v1 as cohort
from simulation.fl_cohort_v1 import ClientProfile
from simulation.wearable import participant_id_for_index

COHORT_ID = "WEARABLE_SIM_FL10_EVAL_HOLDOUT_V1"
BASE_SEED = 20261201            # replicate r uses event-schedule base BASE_SEED + 100*r; participant seed = that base + site index
FIRST_PARTICIPANT_INDEX = 301
COUNT = 16
SITES = 8


def holdout_id(k: int) -> str:
    return f"SIM_FL10_EVAL_{k:02d}"


def profile(k: int) -> ClientProfile:
    if not 0 <= k < COUNT:
        raise ValueError("FL10_HOLDOUT_INDEX_OUT_OF_RANGE")
    site, replicate = k % SITES, k // SITES
    base = BASE_SEED + 100 * replicate
    index = FIRST_PARTICIPANT_INDEX + k
    return ClientProfile(client_id=holdout_id(k), participant_index=index, participant_id=participant_id_for_index(index), session_id=f"SIM_S_FL10_EVAL_{k:02d}_000001",
                         seed=base + site, base_hr_bpm=float(66 + 3 * site), faults=cohort._FAULTS[site], context=cohort._CONTEXT[site], events=cohort._schedule_events(site, base), coverage=cohort._COVERAGE[site])


def profiles() -> tuple[ClientProfile, ...]:
    return tuple(profile(k) for k in range(COUNT))


def build_dataset(p: ClientProfile) -> LocalDataset:
    return build_local_dataset(SyntheticObservedSource(p), SyntheticEventLabelProvider(p))


def manifest_entry(p: ClientProfile, d: LocalDataset, k: int) -> dict[str, Any]:
    return {"holdout_id": p.client_id, "participant_id": p.participant_id, "session_id": p.session_id, "seed": p.seed, "site_condition": cohort.client_id(k % SITES),
            "replicate": k // SITES, "coverage": list(p.coverage), "event_times_s": [e.time_s for e in p.events], "counts": d.counts, "dataset_sha256": d.dataset_sha256}
